parent('Sergey Pivnitskiy', 'Idel Pivnitskiy').
parent('Olga Pivnitskaya', 'Idel Pivnitskiy').
parent('Sergey Pivnitskiy', 'Daniel Pivnitskiy').
parent('Olga Pivnitskaya', 'Daniel Pivnitskiy').
parent('Michail Tronov', 'Sergey Tronov').
parent('Galina Tronova', 'Sergey Tronov').
parent('Michail Tronov', 'Elena Tronova').
parent('Galina Tronova', 'Elena Tronova').
parent('Michail Tronov', 'Olga Pivnitskaya').
parent('Galina Tronova', 'Olga Pivnitskaya').
parent('Alexandr Anohin', 'Sergey Pivnitskiy').
parent('Natalya Pivnitskaya', 'Sergey Pivnitskiy').
parent('Sergey Pinchuk', 'Galina Tronova').
parent('Elena Pinchuk', 'Galina Tronova').
parent('Ivan Tronov', 'Michail Tronov').
parent('Olga Tronova', 'Michail Tronov').
parent('Evsey Pinchuk', 'Sergey Pinchuk').
parent('Maria Pinchuk', 'Sergey Pinchuk').
parent('Yakov Pustoviy', 'Elena Pinchuk').
parent('Marfa Pustovaya', 'Elena Pinchuk').
parent('Alexander Pivnitskiy', 'Natalya Pivnitskaya').
parent('Varvara Pivnitskaya', 'Natalya Pivnitskaya').
parent('Alexandr Anohin', 'Alexandr Anohin').
parent('Nadejda Anohina', 'Alexandr Anohin').
parent('Sergey Tronov', 'Sergey Tronov').
parent('Olga Tronova', 'Sergey Tronov').
parent('Sergey Tronov', 'Ekaterina Tronova').
parent('Olga Tronova', 'Ekaterina Tronova').
parent('Evgeniy Serevec', 'Angelika Serevec').
parent('Elena Tronova', 'Angelika Serevec').
parent('Valeriy Priluchniy', 'Artem Priluchniy').
parent('Angelika Serevec', 'Artem Priluchniy').
parent('Dmitry Shestakov', 'Olga Tronova').
parent('Anna Shestakova', 'Olga Tronova').
parent('Avgust Pivnitskiy', 'Mikolay Pivnitskiy').
parent('Julia Pivnitskaya', 'Mikolay Pivnitskiy').
parent('Avgust Pivnitskiy', 'Michail Pivnitskiy').
parent('Julia Pivnitskaya', 'Michail Pivnitskiy').
parent('Avgust Pivnitskiy', 'Antoni Pivnitskiy').
parent('Julia Pivnitskaya', 'Antoni Pivnitskiy').
parent('Avgust Pivnitskiy', 'Alexander Pivnitskiy').
parent('Julia Pivnitskaya', 'Alexander Pivnitskiy').
 
sex('Sergey Pivnitskiy', m ).
sex('Olga Pivnitskaya', f ).
sex('Idel Pivnitskiy', m ).
sex('Sergey Pivnitskiy', m ).
sex('Olga Pivnitskaya', f ).
sex('Daniel Pivnitskiy', m ).
sex('Michail Tronov', m ).
sex('Galina Tronova', f ).
sex('Sergey Tronov', m ).
sex('Michail Tronov', m ).
sex('Galina Tronova', f ).
sex('Elena Tronova', f ).
sex('Michail Tronov', m ).
sex('Galina Tronova', f ).
sex('Olga Pivnitskaya', f ).
sex('Alexandr Anohin', m ).
sex('Natalya Pivnitskaya', f ).
sex('Sergey Pivnitskiy', m ).
sex('Sergey Pinchuk', m ).
sex('Elena Pinchuk', f ).
sex('Galina Tronova', f ).
sex('Ivan Tronov', m ).
sex('Olga Tronova', f ).
sex('Michail Tronov', m ).
sex('Evsey Pinchuk', m ).
sex('Maria Pinchuk', f ).
sex('Sergey Pinchuk', m ).
sex('Yakov Pustoviy', m ).
sex('Marfa Pustovaya', f ).
sex('Elena Pinchuk', f ).
sex('Alexander Pivnitskiy', m ).
sex('Varvara Pivnitskaya', f ).
sex('Natalya Pivnitskaya', f ).
sex('Alexandr Anohin', m ).
sex('Nadejda Anohina', f ).
sex('Alexandr Anohin', m ).
sex('Sergey Tronov', m ).
sex('Olga Tronova', f ).
sex('Sergey Tronov', m ).
sex('Sergey Tronov', m ).
sex('Olga Tronova', f ).
sex('Ekaterina Tronova', f ).
sex('Evgeniy Serevec', m ).
sex('Elena Tronova', f ).
sex('Angelika Serevec', f ).
sex('Valeriy Priluchniy', m ).
sex('Angelika Serevec', f ).
sex('Artem Priluchniy', m ).
sex('Dmitry Shestakov', m ).
sex('Anna Shestakova', f ).
sex('Olga Tronova', f ).
sex('Avgust Pivnitskiy', m ).
sex('Julia Pivnitskaya', f ).
sex('Mikolay Pivnitskiy', m ).
sex('Avgust Pivnitskiy', m ).
sex('Julia Pivnitskaya', f ).
sex('Michail Pivnitskiy', m ).
sex('Avgust Pivnitskiy', m ).
sex('Julia Pivnitskaya', f ).
sex('Antoni Pivnitskiy', m ).
sex('Avgust Pivnitskiy', m ).
sex('Julia Pivnitskaya', f ).
sex('Alexander Pivnitskiy', m ).
